# -*- coding: utf-8 -*-
"""section-3_data_preprocessing_tools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1w3LfCVENbQSfakvb6_D_QgCz3cAqZ3

**Importing libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""**Importing dataset**"""

data = pd.read_csv("Data.csv")

X = data.iloc[ : , :-1].values
y = data.iloc[ : ,-1].values

X

y

"""**Handling missing data**"""

from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values = np.nan,strategy = 'mean')
impute.fit(X[:,1:3])
X[:,1:3] = impute.transform(X[:,1:3])

X

"""**Handling categorical data**

Independent Variable
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
column_trans = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(column_trans.fit_transform(X))

X

"""Dependent Variable"""

from sklearn.preprocessing import LabelEncoder
label_enc = LabelEncoder()
y = label_enc.fit_transform(y)

y

